singleton
loadBooks
	Instance
		addBook:
			(Book new
				title: 'Where the Crawdads Sing';
				author: (BookAuthor named: 'Delia Owens');
				price: 14.99);
		addBook:
			(Book new
				title: 'A Better Man: A Chief Inspector Gamache Novel';
				author: (BookAuthor named: 'Louise Penny');
				price: 14.99);
		addBook:
			(Book new
				title: 'One Good Deed';
				author: (BookAuthor named: 'David Baldacci');
				price: 14.99);
		addBook:
			(Book new
				title: 'City of Girls: A Novel';
				author: (BookAuthor named: 'Elizabeth Gilbert');
				price: 14.99);
		addBook:
			(Book new
				title: 'Educated: A Memoir';
				author: (BookAuthor named: 'Tara Westover');
				price: 14.99);
		addBook:
			(Book new
				title: 'Becoming';
				author: (BookAuthor named: 'Michelle Obama');
				price: 14.99);
		addBook:
			(Book new
				title: 'Sapiens: A Brief History of Humankind';
				author: (BookAuthor named: 'Yuval Noah Harari');
				price: 14.99);
		addBook:
			(Book new
				title: 'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life';
				author: (BookAuthor named: 'Mark Manson');
				price: 12.99)